package:
  name: kameleon
  version: 6.1.0

source:
  git_url: https://github.com/ccmc/ccmc-software.git


requirements:
  build:
    - python 
    - hdf5 1.8.14
    - cmake >=2.8
    - cdf36
    - boost 1.59.0
    - swig

  run:
    - boost 1.59.0
    - python 
    - cdf36
    - hdf5 1.8.14
    - numpy
    - matplotlib

build:
  number: 0
  binary_relocation: false [linux]
  detect_binary_files_with_prefix: false [linux]


about:
  home: http://ccmc.gsfc.nasa.gov/downloads/Kameleon/Overview.html
  license:  BSD-like
